package Assignment;

public class ExceptionAssignment {

	public static void main(String[] args) {

		
		
//		int a =200; 
//		try {
//		System.out.println(a/0);
//		}
//		catch (ArithmeticException e)
//		{
//			System.out.println("try and catch block runed");
//		}
		//**********************************
//		 
//		try {
//		int ab[]=null; }
//		catch (Exception e)
//		{
//			System.out.println("try and catch the second");
//		}
//		int ab=34; 
//		
//		System.out.println(ab);
		//**************************************************
		
	
		String s = "abc";
		
		
		
		int i = Integer.parseInt(s);
		
		
		
	
		
//		
//		 
//		
//		
		
		
	}

}
